services:
  - type: web
    name: social-klub-api
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: social_klub
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
